// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmzvlevauulcgyfoexuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtenZsZXZhdXVsY2d5Zm9leHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDcyNjMsImV4cCI6MjA2NTgyMzI2M30.SOiAkwoFkqD8XJ9arfsup3fnSu31oWswMNChUfGkF2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);